# Travis-CI Build for libadt
# see travis-ci.org for details

language: c

sudo: required

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake check
  - sudo apt-get install -qq valgrind

before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test
