# Travis-CI Build for libadt
# see travis-ci.org for details

language: c

sudo: required

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential cmake
  - sudo apt-get install -qq valgrind
  - sudo apt install -y clang-format
  - sudo apt install libsubunit-dev
  - wget --no-check-certificate --content-disposition https://github.com/libcheck/check/releases/download/0.14.0/check-0.14.0.tar.gz
  - tar -xvf ./check-0.14.0.tar.gz
  - cd ./check-0.14.0
  - ./configure --enable-subunit
  - make && make check
  - sudo make install
  - cd .. 
before_script:
  - mkdir build

script:
  - cd build
  - cmake ..
  - make
  - make test VERBOSE=1
  - cd .. && bash ./check_code_format.sh
